#!/usr/bin/env python3
"""Generate variant C JS bundle: NO secret, only decoys (true-negative lab).

Variant C proves the verifier does NOT fabricate findings when there is nothing
to find. The bundle contains only decoys and API endpoints — no real secret.

Plants:
  1. Placeholder decoy: "your_api_key_here" (must be rejected)
  2. Low-entropy decoy: "aaaaaaaaaaaaaaaaaa" (must be rejected)
  3. API endpoints (intel extraction still works without secrets)

Usage:
    python3 generate_bundle_c.py

Outputs (git-ignored):
    assets/app.lab001.js   (overwritten)
    expected.local.json    (overwritten)
"""

from __future__ import annotations

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ASSETS = HERE / "assets"
BUNDLE = ASSETS / "app.lab001.js"
EXPECTED = HERE / "expected.local.json"

PLACEHOLDER_DECOY = "your_api_key_here"
LOWENTROPY_DECOY = "a" * 18


BUNDLE_TEMPLATE = """\
// GENERATED by generate_bundle_c.py — variant C (no secret, TN lab). DO NOT COMMIT.
// Self-owned SPA lab bundle for Agent-Alpha JS-secret field-prove.
// This bundle has NO real secret — only decoys. Verifier must return 0 creds.
const config = {{
  // decoys — must ALL be rejected
  secret: "{placeholder_decoy}",
  token: "{lowentropy_decoy}",
  apiKey: "placeholder_value_here",
  baseURL: "/api/v3",
}};

async function loadSettings() {{
  const r = await fetch("/api/v3/settings");
  return r.json();
}}

async function getHealth() {{
  return axios.get("/api/v3/health");
}}

async function submitForm(data) {{
  return fetch("/api/v3/submit", {{ method: "POST", body: JSON.stringify(data) }});
}}

document.getElementById("app").textContent = "Variant C Console (lab) ready";
export {{ loadSettings, getHealth, submitForm }};
"""


def main() -> int:
    ASSETS.mkdir(parents=True, exist_ok=True)

    BUNDLE.write_text(
        BUNDLE_TEMPLATE.format(
            placeholder_decoy=PLACEHOLDER_DECOY,
            lowentropy_decoy=LOWENTROPY_DECOY,
        ),
        encoding="utf-8",
    )

    expected = {
        "bundle_path": "/assets/app.lab001.js",
        "expected_creds_added": 0,
        "expected_secret_kind": "none",
        "expected_secret_service": "none",
        "expected_secret_preview": "",
        "rejected_decoys": [PLACEHOLDER_DECOY, LOWENTROPY_DECOY, "placeholder_value_here"],
        "expected_api_endpoints": [
            "/api/v3/settings",
            "/api/v3/health",
            "/api/v3/submit",
            "/api/v3",
        ],
    }
    EXPECTED.write_text(json.dumps(expected, indent=2) + "\n", encoding="utf-8")

    print("[lab-c] wrote", BUNDLE.relative_to(HERE))
    print("[lab-c] wrote", EXPECTED.relative_to(HERE))
    print("[lab-c] expected_creds_added:", expected["expected_creds_added"])
    print("[lab-c] decoys that must be rejected:", expected["rejected_decoys"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
