#!/usr/bin/env python3
"""Generate the secret-bearing JS bundle for the SPA field-prove lab.

Why a generator instead of a committed bundle:
  - The repo is PUBLIC and GitGuardian is enabled. A committed secret — even a
    synthetic one — trips secret scanning and pollutes world-readable history.
  - So the synthetic secret is generated locally at setup time, written into the
    (git-ignored) bundle + a (git-ignored) ``expected.local.json`` the field-prove
    reads. Nothing sensitive ever lands in git.

What it plants (this is the lab's KNOWN GROUND TRUTH):
  1. ONE real-shaped synthetic secret that MUST be detected:
        const apiKey = "<32-char high-entropy generic value>";
     -> matches JS_SECRET_PATTERNS "generic_assign", passes _looks_like_secret()
        (len>=16, not in placeholder denylist, Shannon entropy>=3.5, not all-same-char).
  2. TWO decoys that MUST be rejected (proves the anti-#3 discriminator on a REAL
     target, not just in unit tests). Their KEY NAMES match the generic_assign
     pattern so they reach _looks_like_secret and are rejected there:
        secret: "your_api_key_here";          # placeholder denylist hit
        token:  "aaaaaaaaaaaaaaaaaa";          # all-same-char -> rejected
  3. Fake API endpoints extracted as attack-surface INTEL (not creds):
        /api/v1/users, /api/v1/orders, baseURL /api/v1, /graphql

Deliberately NO provider-format keys (AKIA…, sk_live_…, ghp_…): those would trip
GitGuardian / GitHub secret scanning by shape even though synthetic. generic_assign
is the safe, representative vector for a self-owned lab.

Usage:
    python3 generate_bundle.py                 # random synthetic secret each run
    LAB_SYNTHETIC_SECRET=<value> python3 generate_bundle.py   # pin a fixed value

Outputs (both git-ignored):
    assets/app.lab001.js
    expected.local.json
"""

from __future__ import annotations

import json
import math
import os
import pathlib
import secrets

HERE = pathlib.Path(__file__).resolve().parent
ASSETS = HERE / "assets"
BUNDLE = ASSETS / "app.lab001.js"
EXPECTED = HERE / "expected.local.json"

# These MUST stay in sync with the probe's discriminator thresholds so the lab is
# an honest test of the deployed contract, not a softer one.
MIN_LEN = 16
MIN_ENTROPY = 3.5

PLACEHOLDER_DECOY = "your_api_key_here"  # in JS_SECRET_PLACEHOLDER_DENYLIST
LOWENTROPY_DECOY = "a" * 18  # all-same-char -> rejected


def _shannon_entropy(s: str) -> float:
    if not s:
        return 0.0
    freq: dict[str, int] = {}
    for c in s:
        freq[c] = freq.get(c, 0) + 1
    n = len(s)
    return -sum((f / n) * math.log2(f / n) for f in freq.values())


def _mask(value: str) -> str:
    """Mirror js_secret_probe._mask: first4****last4."""
    if len(value) <= 8:
        return "****"
    return f"{value[:4]}****{value[-4:]}"


def _make_secret() -> str:
    pinned = os.environ.get("LAB_SYNTHETIC_SECRET")
    if pinned:
        secret = pinned
    else:
        # token_urlsafe(24) -> ~32 chars, high entropy, generic (not provider-shaped).
        secret = secrets.token_urlsafe(24)
    if len(secret) < MIN_LEN:
        raise SystemExit(f"synthetic secret too short ({len(secret)} < {MIN_LEN})")
    if _shannon_entropy(secret) < MIN_ENTROPY:
        raise SystemExit("synthetic secret entropy too low; regenerate")
    if len(set(secret)) == 1:
        raise SystemExit("synthetic secret is all-same-char; regenerate")
    return secret


BUNDLE_TEMPLATE = """\
// GENERATED by generate_bundle.py — DO NOT COMMIT (git-ignored).
// Generic self-owned SPA lab bundle for Agent-Alpha JS-secret field-prove.
const config = {{
  // (1) real-shaped synthetic secret — MUST be detected by scan_js_for_secrets
  apiKey: "{secret}",
  // (2) decoys — key names MUST match generic_assign (api_key|secret|token|password)
  //     so they REACH _looks_like_secret and get rejected THERE (anti-#3), not
  //     skipped at the regex stage.
  secret: "{placeholder_decoy}",
  token: "{lowentropy_decoy}",
  baseURL: "/api/v1",
}};

async function loadUsers() {{
  const r = await fetch("/api/v1/users", {{ headers: {{ "x-api-key": config.apiKey }} }});
  return r.json();
}}

async function loadOrders() {{
  const r = await axios.get("/api/v1/orders");
  return r.data;
}}

async function graph(q) {{
  return fetch("/graphql", {{ method: "POST", body: JSON.stringify({{ query: q }}) }});
}}

document.getElementById("app").textContent = "Acme Internal Console (lab) ready";
export {{ loadUsers, loadOrders, graph }};
"""


def main() -> int:
    secret = _make_secret()
    ASSETS.mkdir(parents=True, exist_ok=True)
    BUNDLE.write_text(
        BUNDLE_TEMPLATE.format(
            secret=secret,
            placeholder_decoy=PLACEHOLDER_DECOY,
            lowentropy_decoy=LOWENTROPY_DECOY,
        ),
        encoding="utf-8",
    )

    expected = {
        "bundle_path": "/assets/app.lab001.js",
        "expected_creds_added": 1,
        "expected_secret_kind": "generic_assign",
        "expected_secret_service": "generic",
        "expected_secret_preview": _mask(secret),
        "rejected_decoys": [PLACEHOLDER_DECOY, LOWENTROPY_DECOY],
        "expected_api_endpoints": [
            "/api/v1/users",
            "/api/v1/orders",
            "/api/v1",
            "/graphql",
        ],
    }
    EXPECTED.write_text(json.dumps(expected, indent=2) + "\n", encoding="utf-8")

    print("[lab] wrote", BUNDLE.relative_to(HERE))
    print("[lab] wrote", EXPECTED.relative_to(HERE))
    print("[lab] planted secret preview:", expected["expected_secret_preview"])
    print("[lab] expected_creds_added:", expected["expected_creds_added"])
    print("[lab] decoys that must be rejected:", expected["rejected_decoys"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
