#!/usr/bin/env python3
"""Generate variant B JS bundle: provider-format secrets (AWS + Stripe + GitHub).

Variant B proves the verifier detects DIFFERENT secret patterns (not just
generic_assign). Uses provider-shaped synthetic secrets that are git-ignored.

Plants:
  1. AWS access key: AKIA + 16 uppercase alphanumerics
  2. Stripe live key: sk_live_ + 24+ alphanumerics
  3. GitHub PAT: ghp_ + 36 alphanumerics
  4. One decoy: placeholder string (must be rejected)

No generic_assign secret — this variant proves provider-pattern detection.

Usage:
    python3 generate_bundle_b.py

Outputs (git-ignored):
    assets/app.lab001.js   (overwritten)
    expected.local.json    (overwritten)
"""

from __future__ import annotations

import json
import pathlib
import random
import string

HERE = pathlib.Path(__file__).resolve().parent
ASSETS = HERE / "assets"
BUNDLE = ASSETS / "app.lab001.js"
EXPECTED = HERE / "expected.local.json"

PLACEHOLDER_DECOY = "your_api_key_here"


def _mask(value: str) -> str:
    if len(value) <= 8:
        return "****"
    return f"{value[:4]}****{value[-4:]}"


def _make_aws_key() -> str:
    return "AKIA" + "".join(random.choices(string.ascii_uppercase + string.digits, k=16))


def _make_stripe_key() -> str:
    return "sk_live_" + "".join(random.choices(string.ascii_letters + string.digits, k=28))


def _make_github_pat() -> str:
    return "ghp_" + "".join(random.choices(string.ascii_letters + string.digits, k=36))


BUNDLE_TEMPLATE = """\
// GENERATED by generate_bundle_b.py — variant B (provider patterns). DO NOT COMMIT.
// Self-owned SPA lab bundle for Agent-Alpha JS-secret field-prove.
const config = {{
  awsAccessKeyId: "{aws_key}",
  stripeSecretKey: "{stripe_key}",
  githubToken: "{gh_token}",
  // decoy — placeholder, must be rejected
  secret: "{decoy}",
  baseURL: "/api/v2",
}};

async function fetchProfile() {{
  const r = await fetch("/api/v2/profile", {{ headers: {{ Authorization: "Bearer " + config.githubToken }} }});
  return r.json();
}}

async function charge(amount) {{
  return axios.post("/api/v2/charge", {{ amount }});
}}

async function listBuckets() {{
  return fetch("/api/v2/buckets");
}}

document.getElementById("app").textContent = "Variant B Console (lab) ready";
export {{ fetchProfile, charge, listBuckets }};
"""


def main() -> int:
    ASSETS.mkdir(parents=True, exist_ok=True)

    aws_key = _make_aws_key()
    stripe_key = _make_stripe_key()
    gh_token = _make_github_pat()

    BUNDLE.write_text(
        BUNDLE_TEMPLATE.format(
            aws_key=aws_key,
            stripe_key=stripe_key,
            gh_token=gh_token,
            decoy=PLACEHOLDER_DECOY,
        ),
        encoding="utf-8",
    )

    expected = {
        "bundle_path": "/assets/app.lab001.js",
        "expected_creds_added": 3,
        "expected_secret_kind": "aws_access_key",
        "expected_secret_service": "aws",
        "expected_secret_preview": _mask(aws_key),
        "rejected_decoys": [PLACEHOLDER_DECOY],
        "expected_api_endpoints": [
            "/api/v2/profile",
            "/api/v2/charge",
            "/api/v2/buckets",
            "/api/v2",
        ],
    }
    EXPECTED.write_text(json.dumps(expected, indent=2) + "\n", encoding="utf-8")

    print("[lab-b] wrote", BUNDLE.relative_to(HERE))
    print("[lab-b] wrote", EXPECTED.relative_to(HERE))
    print("[lab-b] planted AWS key preview:", _mask(aws_key))
    print("[lab-b] planted Stripe key preview:", _mask(stripe_key))
    print("[lab-b] planted GitHub PAT preview:", _mask(gh_token))
    print("[lab-b] expected_creds_added:", expected["expected_creds_added"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
